global:
  imageRegistry: ""

frontend:
  repository: "snaplink-web"
  imageTag: "latest"
  servicePort: 80
  domain: "snaplink.com"

api:
  repository: "snaplink-api"
  imageTag: "latest"
  servicePort: 5000

db:
  repository: "snaplink-db"
  imageTag: "latest"
  servicePort: 5432
  user: ""
  password: ""
  name: "urlshort"

redis:
  repository: "snaplink-cache"
  imageTag: "latest"
  servicePort: 6379


