repoURL: "https://github.com/bobhatevishal/Helm-deployment-app.git"
targetRevision: main
environments:
  - dev
  - qa
  - uat
  - prod
namespacePrefix: snaplink

applications:
  - name: api
    component: api
  - name: cache
    component: cache
  - name: db
    component: db
  - name: frontend
    component: frontend
